"""
Composable SQLAlchemy mixins for all domain models.

Design (D2 from design.md):
    UUIDMixin         — id UUID PK, generated in Python (not DB).
    TimestampMixin    — created_at (immutable), updated_at (auto-refresh).
    SoftDeleteMixin   — deleted_at nullable; marks logical deletion.
    TenantMixin       — tenant_id UUID FK → tenants.id, not null, indexed.
    TenantScopedBase  — convenience alias = all four above for business entities.

Usage:
    # Root entity (no tenant_id):
    class Tenant(Base, UUIDMixin, TimestampMixin, SoftDeleteMixin): ...

    # Business entity:
    class Alumno(Base, TenantScopedBase): ...
"""
import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import DateTime, ForeignKey, Index, func
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


# ---------------------------------------------------------------------------
# UUIDMixin — opaque UUID primary key, generated in the application layer.
# ---------------------------------------------------------------------------

class UUIDMixin:
    """UUID primary key generated by the application (not the DB)."""

    id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
    )


# ---------------------------------------------------------------------------
# TimestampMixin — audit timestamps, managed server-side.
# ---------------------------------------------------------------------------

class TimestampMixin:
    """Automatic created_at / updated_at timestamps."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


# ---------------------------------------------------------------------------
# SoftDeleteMixin — logical deletion via deleted_at.
# ---------------------------------------------------------------------------

class SoftDeleteMixin:
    """Soft-delete support: deleted_at=None → active; non-null → logically deleted."""

    deleted_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
    )


# ---------------------------------------------------------------------------
# TenantMixin — row-level multi-tenancy via tenant_id FK.
# ---------------------------------------------------------------------------

class TenantMixin:
    """
    Multi-tenancy: every business entity references the owning tenant.

    The FK must point to tenants.id.  The column is indexed so that
    queries scoped to a tenant are efficient.
    """

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )


# ---------------------------------------------------------------------------
# TenantScopedBase — convenience composite for all business entities.
# ---------------------------------------------------------------------------

class TenantScopedBase(UUIDMixin, TenantMixin, TimestampMixin, SoftDeleteMixin):
    """
    Convenience base for ALL business entities (non-root).

    Provides:
        id           UUID PK (UUIDMixin)
        tenant_id    UUID FK → tenants.id (TenantMixin)
        created_at   DateTime (TimestampMixin)
        updated_at   DateTime (TimestampMixin)
        deleted_at   DateTime nullable (SoftDeleteMixin)
    """
